AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 160

Gemspec/OrderedDependencies:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
